package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var (
	aliasFD             int
	aliasPlain          bool
	aliasNonInteractive bool
	aliasDebug          bool
)

var aliasCmd = &cobra.Command{
	Use:   "alias <name>",
	Short: "Print a shell function wrapper for directory navigation",
	Long: `Print a shell function that wraps git-wt to enable directory navigation.

Add to your shell config:
    eval "$(git-wt alias gwt)"

The wrapper captures the worktree path on fd N (default 3) for the
go/new/rm commands and changes directory in the parent shell. Other
commands pass through untouched.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		if !validIdentifier(name) {
			return fmt.Errorf("invalid alias name %q: must be a valid shell identifier", name)
		}
		if aliasFD < 3 || aliasFD > 9 {
			return fmt.Errorf("--fd must be in 3-9 (got %d)", aliasFD)
		}
		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("locate git-wt binary: %w", err)
		}
		fmt.Print(renderAlias(name, exe, aliasFD, aliasPlain, aliasNonInteractive, aliasDebug))
		return nil
	},
}

func init() {
	rootCmd.AddCommand(aliasCmd)
	aliasCmd.Flags().IntVar(&aliasFD, "fd", 3, "file descriptor for the wrapper protocol (3-9)")
	aliasCmd.Flags().BoolVar(&aliasPlain, "plain", false, "bake --plain into the wrapper")
	aliasCmd.Flags().BoolVarP(&aliasNonInteractive, "non-interactive", "n", false, "bake --non-interactive into the wrapper")
	aliasCmd.Flags().BoolVar(&aliasDebug, "debug", false, "include debug logging in the wrapper")
}

func validIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r == '_':
			// always allowed
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// aliasTemplate is the shell-function template. Substitutions:
//
//	{{NAME}}     alias name (also used in debug prefix)
//	{{BIN}}      path to the git-wt binary, shell-quoted
//	{{FD}}       integer fd number
//	{{FLAGS}}    pre-baked global flags, e.g. " --plain --non-interactive" (or empty)
//	{{DBG_LOAD}} optional `echo "[name] loaded …" >&2` line
//	{{DBG_RUN}}  optional `echo "[name] running …" >&2` line
//	{{DBG_CAP}}  optional `echo "[name] captured …" >&2` line
const aliasTemplate = `# git-wt shell wrapper — generated by: git-wt alias {{NAME}}
{{NAME}}() {
    local bin={{BIN}}
    local fd={{FD}}
{{DBG_LOAD}}    case "$1" in
        go|new|rm)
{{DBG_RUN}}            local target rc
            target=$("$bin" --fd "$fd"{{FLAGS}} "$@" "$fd">&1 1>&2)
            rc=$?
{{DBG_CAP}}            if [ "$rc" -eq 0 ] && [ -n "$target" ]; then
                cd "$target" || return
            fi
            return "$rc"
            ;;
        *)
            "$bin"{{FLAGS}} "$@"
            ;;
    esac
}
`

// renderAlias produces the shell function source for `name`.
func renderAlias(name, exe string, fdN int, plain, nonInteractive, debug bool) string {
	var flags []string
	if plain {
		flags = append(flags, "--plain")
	}
	if nonInteractive {
		flags = append(flags, "--non-interactive")
	}
	flagsLine := ""
	if len(flags) > 0 {
		flagsLine = " " + strings.Join(flags, " ")
	}
	dbg := func(indent, msg string) string {
		if !debug {
			return ""
		}
		return fmt.Sprintf("%secho \"[%s] %s\" >&2\n", indent, name, msg)
	}

	r := strings.NewReplacer(
		"{{NAME}}", name,
		"{{BIN}}", shellQuote(exe),
		"{{FD}}", fmt.Sprintf("%d", fdN),
		"{{FLAGS}}", flagsLine,
		"{{DBG_LOAD}}", dbg("    ", fmt.Sprintf("call: bin=%s fd=%d args=$*", exe, fdN)),
		"{{DBG_RUN}}", dbg("            ", "running with fd capture"),
		"{{DBG_CAP}}", dbg("            ", "captured: '$target' rc=$rc"),
	)
	return r.Replace(aliasTemplate)
}

// shellQuote single-quotes s for safe inclusion in a POSIX shell command.
// Single quotes inside s are emitted as `'\''`.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
