package cli

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/shhac/git-wt/internal/config"
)

// "bakeX" names emphasize that these flags get baked into the generated shell
// wrapper at alias-generation time — distinct from the global flagX variables
// in root.go which control the current invocation.
var (
	bakeFD             int
	bakePlain          bool
	bakeNonInteractive bool
	bakeDebug          bool
	bakeNoCompletion   bool
)

var aliasCmd = &cobra.Command{
	Use:   "alias <name>",
	Short: "Print a shell function wrapper for directory navigation",
	Long: `Print a shell function that wraps git-wt to enable directory navigation.

Add to your shell config:
    eval "$(git-wt alias gwt)"

The wrapper captures the worktree path on fd N (default 3) for the
go/new/add/eject/rm commands and changes directory in the parent
shell. Other commands pass through untouched.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		if !validIdentifier(name) {
			return fmt.Errorf("invalid alias name %q: must be a valid shell identifier", name)
		}
		if err := config.ValidateFD(strconv.Itoa(bakeFD)); err != nil {
			return fmt.Errorf("--fd %w", err)
		}
		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("locate git-wt binary: %w", err)
		}
		fmt.Print(renderAlias(name, exe, bakeFD, bakePlain, bakeNonInteractive, bakeDebug, !bakeNoCompletion))
		return nil
	},
}

func init() {
	rootCmd.AddCommand(aliasCmd)
	aliasCmd.Flags().IntVar(&bakeFD, "fd", config.FDMin, fmt.Sprintf("fd to bake into the wrapper protocol (%d-%d)", config.FDMin, config.FDMax))
	aliasCmd.Flags().BoolVar(&bakePlain, "plain", false, "bake --plain into the wrapper")
	aliasCmd.Flags().BoolVarP(&bakeNonInteractive, "non-interactive", "n", false, "bake --non-interactive into the wrapper")
	aliasCmd.Flags().BoolVar(&bakeDebug, "debug", false, "bake debug logging into the wrapper")
	aliasCmd.Flags().BoolVar(&bakeNoCompletion, "no-completion", false, "skip the tab-completion binding (default: bind alias completion to git-wt's)")
}

func validIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r == '_':
			// always allowed
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// aliasTemplate is the shell-function template. Substitutions:
//
//	{{NAME}}     alias name (also used in debug prefix)
//	{{BIN}}      path to the git-wt binary, shell-quoted
//	{{FD}}       integer fd number
//	{{FLAGS}}    pre-baked global flags, e.g. " --plain --non-interactive" (or empty)
//	{{DBG_LOAD}} optional `echo "[name] loaded …" >&2` line
//	{{DBG_RUN}}  optional `echo "[name] running …" >&2` line
//	{{DBG_CAP}}  optional `echo "[name] captured …" >&2` line
//
// The fd number ({{FD}}) is baked literally into the redirect because bash
// expands variables AFTER parsing the redirect token — `"$fd">&1` would be
// read as a positional arg, not a redirect.
//
// The arg walk before the case is what makes `gwt --debug go` (flag before
// subcommand) take the cd-capable branch. A naive `case "$1"` only matches
// when the subcommand is the literal first arg, which breaks for every
// leading global flag (`--debug`, `--plain`, `-n`, `--fd N`).
const aliasTemplate = `# git-wt shell wrapper — generated by: git-wt alias {{NAME}}
{{NAME}}() {
    local bin={{BIN}}
{{DBG_LOAD}}    # Find the subcommand by skipping any leading global flags. --fd takes a
    # value (skipped via _skip); other globals are booleans. Stops at "--" or
    # at the first non-flag arg.
    local _sub="" _skip=0 _arg
    for _arg in "$@"; do
        if [ "$_skip" = 1 ]; then _skip=0; continue; fi
        case "$_arg" in
            --fd=*) ;;
            --fd) _skip=1 ;;
            --) break ;;
            -*) ;;
            *) _sub="$_arg"; break ;;
        esac
    done

    case "$_sub" in
        go|new|add|eject|rm)
{{DBG_RUN}}            local target rc
            target=$("$bin" --fd {{FD}}{{FLAGS}} "$@" {{FD}}>&1 1>&2)
            rc=$?
{{DBG_CAP}}            if [ "$rc" -eq 0 ] && [ -n "$target" ]; then
                cd "$target" || return
            fi
            return "$rc"
            ;;
        *)
            "$bin"{{FLAGS}} "$@"
            ;;
    esac
}
{{COMPLETION_BINDING}}`

// completionBindingTemplate ties the wrapper's tab-completion to the
// binary's existing completion logic, so once the user has installed
// `git-wt completion <shell>` into their shell's completion path,
// `{{NAME}} go <TAB>` etc. work without a second setup step.
//
// Each branch is a no-op when the completion script hasn't been
// installed (bash: __start_git-wt doesn't exist; zsh: compdef errors
// silently into nowhere thanks to 2>/dev/null). That keeps the
// wrapper safe to source in a shell with no completion configured.
const completionBindingTemplate = `
# Bind tab-completion for the alias to git-wt's own completion logic.
# A no-op if `+"`"+`git-wt completion <shell>`+"`"+` hasn't been sourced yet.
if [ -n "${ZSH_VERSION-}" ]; then
    compdef {{NAME}}=git-wt 2>/dev/null
elif [ -n "${BASH_VERSION-}" ] && declare -F __start_git-wt >/dev/null 2>&1; then
    complete -o default -F __start_git-wt {{NAME}}
fi
`

// renderAlias produces the shell function source for `name`.
func renderAlias(name, exe string, fdN int, plain, nonInteractive, debug, bindCompletion bool) string {
	var flags []string
	if plain {
		flags = append(flags, "--plain")
	}
	if nonInteractive {
		flags = append(flags, "--non-interactive")
	}
	flagsLine := ""
	if len(flags) > 0 {
		flagsLine = " " + strings.Join(flags, " ")
	}
	dbg := func(indent, msg string) string {
		if !debug {
			return ""
		}
		return fmt.Sprintf("%secho \"[%s] %s\" >&2\n", indent, name, msg)
	}

	completionBlock := ""
	if bindCompletion {
		completionBlock = strings.ReplaceAll(completionBindingTemplate, "{{NAME}}", name)
	}

	r := strings.NewReplacer(
		"{{NAME}}", name,
		"{{BIN}}", shellQuote(exe),
		"{{FD}}", fmt.Sprintf("%d", fdN),
		"{{FLAGS}}", flagsLine,
		"{{DBG_LOAD}}", dbg("    ", fmt.Sprintf("call: bin=%s fd=%d args=$*", exe, fdN)),
		"{{DBG_RUN}}", dbg("            ", "running with fd capture"),
		"{{DBG_CAP}}", dbg("            ", "captured: '$target' rc=$rc"),
		"{{COMPLETION_BINDING}}", completionBlock,
	)
	return r.Replace(aliasTemplate)
}
