package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var completionCmd = &cobra.Command{
	Use:       "completion <bash|zsh|fish|powershell>",
	Short:     "Generate a shell completion script",
	ValidArgs: []string{"bash", "zsh", "fish", "powershell"},
	Args:      cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
	Long: `Generate a shell completion script for the given shell.

Cobra emits the actual completion script; this command is a thin
wrapper. The completion script supports tab-completion for command
names, flags, and (where wired) dynamic argument values like the
list of existing worktree branches for ` + "`go`" + ` and ` + "`rm`" + `.

Setup:

  # bash — one-time
  git-wt completion bash > ~/.local/share/bash-completion/completions/git-wt

  # zsh — one-time (path must be in $fpath; ~/.zsh/completions is a common choice)
  git-wt completion zsh > ~/.zsh/completions/_git-wt

  # fish
  git-wt completion fish > ~/.config/fish/completions/git-wt.fish

  # powershell
  git-wt completion powershell | Out-String | Invoke-Expression

The shell function generated by ` + "`git-wt alias gwt`" + ` automatically
binds tab-completion for the alias to git-wt's completion, so once
the completion script above is in place, ` + "`gwt go <TAB>`" + ` and
` + "`gwt rm <TAB>`" + ` also complete.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		switch args[0] {
		case "bash":
			return cmd.Root().GenBashCompletionV2(os.Stdout, true)
		case "zsh":
			return cmd.Root().GenZshCompletion(os.Stdout)
		case "fish":
			return cmd.Root().GenFishCompletion(os.Stdout, true)
		case "powershell":
			return cmd.Root().GenPowerShellCompletionWithDesc(os.Stdout)
		}
		return fmt.Errorf("unsupported shell: %s", args[0])
	},
}

func init() {
	rootCmd.AddCommand(completionCmd)
}
