name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: ['0.15.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Run unit tests
        run: zig test src/main.zig

      - name: Run integration tests
        run: zig test src/integration_tests.zig

      - name: Build release binary
        run: zig build -Doptimize=ReleaseFast

      - name: Verify binary works
        run: ./zig-out/bin/git-wt --version
